AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16:
      size:
        width: 840
        height: 350
      position:
        x: 140
        'y': 50
      z: 0
      embeds:
        - f2e65b0e-490e-4351-a5c2-6f8ee83caf46
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - bee4d0be-ca67-4637-8b62-b2653705184f
        - ac8db543-9863-4177-a0c8-224411b5ad55
    ac8db543-9863-4177-a0c8-224411b5ad55:
      size:
        width: 230
        height: 240
      position:
        x: 220
        'y': 81
      z: 1
      parent: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
      embeds:
        - 5fcc62cd-d807-458f-ae1b-70153e262281
        - c7179794-0a42-4d5d-b493-95cf6d6aa709
      iscontainedinside:
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
    c7179794-0a42-4d5d-b493-95cf6d6aa709:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 200
      z: 2
      parent: ac8db543-9863-4177-a0c8-224411b5ad55
      embeds: []
      iscontainedinside:
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
      dependson:
        - 2584e6ce-312f-4b54-a82a-d978fc979f95
    bee4d0be-ca67-4637-8b62-b2653705184f:
      size:
        width: 60
        height: 60
      position:
        x: 490
        'y': 90
      z: 1
      parent: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
      embeds: []
      iscontainedinside:
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
    1b5d3e90-0328-4d68-8a1d-535be36cd96d:
      size:
        width: 60
        height: 60
      position:
        x: -220
        'y': 120
      z: 0
      embeds: []
    3c321c22-4300-435f-bfde-f8f0889e46fb:
      source:
        id: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
      target:
        id: 1b5d3e90-0328-4d68-8a1d-535be36cd96d
      z: 0
    653b7ba5-e1ca-42df-be3d-79f905a44566:
      size:
        width: 180
        height: 130
      position:
        x: 570
        'y': 170
      z: 1
      parent: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
      embeds:
        - 2584e6ce-312f-4b54-a82a-d978fc979f95
      dependson:
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
    2584e6ce-312f-4b54-a82a-d978fc979f95:
      size:
        width: 60
        height: 60
      position:
        x: 610
        'y': 190
      z: 2
      parent: 653b7ba5-e1ca-42df-be3d-79f905a44566
      embeds: []
      iscontainedinside:
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
        - 653b7ba5-e1ca-42df-be3d-79f905a44566
      dependson:
        - 1b5d3e90-0328-4d68-8a1d-535be36cd96d
    86cc9fe0-2fbc-4d6a-9f78-c65e160058f6:
      source:
        id: 653b7ba5-e1ca-42df-be3d-79f905a44566
      target:
        id: ac8db543-9863-4177-a0c8-224411b5ad55
      z: 1
    f2e65b0e-490e-4351-a5c2-6f8ee83caf46:
      size:
        width: 190
        height: 210
      position:
        x: 780
        'y': 100
      z: 1
      parent: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
      embeds:
        - c9c2d203-6899-4701-968e-0ccded9c1bcd
      iscontainedinside:
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
        - ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
    5fcc62cd-d807-458f-ae1b-70153e262281:
      size:
        width: 60
        height: 60
      position:
        x: 240
        'y': 200
      z: 2
      parent: ac8db543-9863-4177-a0c8-224411b5ad55
      embeds: []
      iscontainedinside:
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
        - ac8db543-9863-4177-a0c8-224411b5ad55
      dependson:
        - c7179794-0a42-4d5d-b493-95cf6d6aa709
    c9c2d203-6899-4701-968e-0ccded9c1bcd:
      size:
        width: 160
        height: 160
      position:
        x: 800
        'y': 130
      z: 2
      parent: f2e65b0e-490e-4351-a5c2-6f8ee83caf46
      embeds:
        - 9f846361-cdfa-4eba-9717-08b7283c256c
    9f846361-cdfa-4eba-9717-08b7283c256c:
      size:
        width: 60
        height: 60
      position:
        x: 820
        'y': 160
      z: 3
      parent: c9c2d203-6899-4701-968e-0ccded9c1bcd
      embeds: []
      isassociatedwith:
        - 5fcc62cd-d807-458f-ae1b-70153e262281
      iscontainedinside:
        - c9c2d203-6899-4701-968e-0ccded9c1bcd
        - c9c2d203-6899-4701-968e-0ccded9c1bcd
        - c9c2d203-6899-4701-968e-0ccded9c1bcd
        - c9c2d203-6899-4701-968e-0ccded9c1bcd
    fdce7d18-e2e7-4f87-a387-aa652abcd19a:
      source:
        id: 9f846361-cdfa-4eba-9717-08b7283c256c
      target:
        id: 5fcc62cd-d807-458f-ae1b-70153e262281
      z: 4
    387d9fb9-c005-4873-8aa1-33b5082a2021:
      source:
        id: 5fcc62cd-d807-458f-ae1b-70153e262281
      target:
        id: c7179794-0a42-4d5d-b493-95cf6d6aa709
      z: 4
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ba850c0e-9eaa-4d23-a9f1-fecb5bbd3c16
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac8db543-9863-4177-a0c8-224411b5ad55
  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - GroupSet:
            - !Ref WebServerSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
        - SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        'AWS::CloudFormation::Init': null
        configSets:
          All:
            - ConfigureSampleApp
        ConfigureSampleApp:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: !Join 
                - |+

                - - >-
                    <h1>Congratulations, you have successfully launched the AWS
                    CloudFormation sample.</h1>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
        id: c7179794-0a42-4d5d-b493-95cf6d6aa709
    DependsOn:
      - PublicRoute
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: Allow access from HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bee4d0be-ca67-4637-8b62-b2653705184f
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1b5d3e90-0328-4d68-8a1d-535be36cd96d
  EC2VPCGXM5B:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3c321c22-4300-435f-bfde-f8f0889e46fb
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 653b7ba5-e1ca-42df-be3d-79f905a44566
    DependsOn:
      - MyVPC
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2584e6ce-312f-4b54-a82a-d978fc979f95
    DependsOn:
      - InternetGateway
  EC2SRTA2KCPT:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 86cc9fe0-2fbc-4d6a-9f78-c65e160058f6
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f2e65b0e-490e-4351-a5c2-6f8ee83caf46
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c9c2d203-6899-4701-968e-0ccded9c1bcd
  PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      NatGatewayId: !Ref NatGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9f846361-cdfa-4eba-9717-08b7283c256c
  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5fcc62cd-d807-458f-ae1b-70153e262281
    DependsOn:
      - WebServerInstance
